### ISSUE TITLE
Sudoers content span multiple lines

### ISSUE THREAD

**Issue by seapasulli** [justinclayton/puppet-module-sudo#7]
I'm new. (yup new period). So I may be doing something wrong, but I can't seem to get content to span multiple lines correctly in puppet.

I am using foreman + puppet currently and I am using your module to create sudoers files per user in a staff group. I need to disable tty for a specific user and I can't seem to get it to work correctly. Is there a way to have content span multiple lines?

**Comment by seapasulli** [comment]
Ah I'm dumb. Sorry to have bugged you. 

My yaml hash now looks like this::

``` yaml
User:
    ensure: present
    content: |
        Defaults:User !requiretty
        User ALL=(ALL) NOPASSWD: ALL

User2:
   blah
```

Sorry to have bugged you! %_%
